src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'commentaires')]
    #[ORM\JoinColumn(name: "id_utilisateur", referencedColumnName: "id", nullable: false)]
    private ?Utilisateur $utilisateur = null;

    #[ORM\ManyToOne(targetEntity: Recette::class)]
    #[ORM\JoinColumn(name: "id_recette", referencedColumnName: "id", nullable: false)]
    private ?Recette $recette = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $texte = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_commentaire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getRecette(): ?Recette
    {
        return $this->recette;
    }

    public function setRecette(Recette $recette): static
    {
        $this->recette = $recette;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): static
    {
        $this->texte = $texte;

        return $this;
    }

    public function getDateCommentaire(): ?\DateTimeInterface
    {
        return $this->date_commentaire;
    }

    public function setDateCommentaire(\DateTimeInterface $date_commentaire): static
    {
        $this->date_commentaire = $date_commentaire;

        return $this;
    }
}

src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class)]
    #[ORM\JoinColumn(name: "id_utilisateur", referencedColumnName: "id", nullable: false)]
    private ?Utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Commentaire::class, orphanRemoval: true, cascade: ['remove'])]
    private Collection $commentaires;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Etape::class, cascade: ['persist', 'remove'])]
    private Collection $etapes;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Detenir::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $detenir;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Utiliser::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $utiliser;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Note::class, cascade: ['remove'])]
    private Collection $notes;

    public function __construct()
    {
        $this->etapes = new ArrayCollection();
        $this->detenir = new ArrayCollection();
        $this->utiliser = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->commentaires = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getEtapes(): Collection
    {
        return $this->etapes;
    }

    public function addEtape(Etape $etape): self
    {
        if (!$this->etapes->contains($etape)) {
            $this->etapes[] = $etape;
            $etape->setRecette($this);
        }

        return $this;
    }

    public function removeEtape(Etape $etape): self
    {
        if ($this->etapes->removeElement($etape)) {
            if ($etape->getRecette() === $this) {
                $etape->setRecette(null);
            }
        }

        return $this;
    }

    public function getDetenir(): Collection
    {
        return $this->detenir;
    }

    public function addDetenir(Detenir $d): self
    {
        if (!$this->detenir->contains($d)) {
            $this->detenir[] = $d;
            $d->setRecette($this);
        }

        return $this;
    }

    public function removeDetenir(Detenir $d): self
    {
        if ($this->detenir->removeElement($d)) {
            if ($d->getRecette() === $this) {
                $d->setRecette(null);
            }
        }

        return $this;
    }

    public function getUtiliser(): Collection
    {
        return $this->utiliser;
    }

    public function addUtiliser(Utiliser $u): self
    {
        if (!$this->utiliser->contains($u)) {
            $this->utiliser[] = $u;
            $u->setRecette($this);
        }

        return $this;
    }

    public function removeUtiliser(Utiliser $u): self
    {
        if ($this->utiliser->removeElement($u)) {
            if ($u->getRecette() === $this) {
                $u->setRecette(null);
            }
        }

        return $this;
    }

    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setRecette($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            if ($note->getRecette() === $this) {
                $note->setRecette(null);
            }
        }

        return $this;
    }

    public function getNoteMoyenne(): ?float
    {
        $notes = $this->getNotes();
        if (count($notes) === 0) {
            return 0;
        }

        $somme = 0;
        foreach ($notes as $note) {
            $somme += $note->getNote();
        }

        return round($somme / count($notes), 2);
    }

    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }
    public function getUstensiles(): array
    {
        $ustensiles = [];
        foreach ($this->utiliser as $utilisation) {
            $ustensile = $utilisation->getUstensile();
            if ($ustensile !== null) {
                $ustensiles[] = $ustensile;
            }
        }
        return $ustensiles;
    }

}

src/Entity/Utilisateur.php
<?php


namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $role = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Assert\Email(message: "L'adresse e-mail n'est pas valide.")]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $mdp = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_inscription = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo_profil = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $jetonReinitialisation = null;


    public function getJetonReinitialisation(): ?string
    {
        return $this->jetonReinitialisation;
    }

    public function setJetonReinitialisation(?string $jetonReinitialisation): static
    {
        $this->jetonReinitialisation = $jetonReinitialisation;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): static
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): static
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getPhotoProfil(): ?string
    {
        return $this->photo_profil;
    }

    public function setPhotoProfil(?string $photo_profil): static
    {
        $this->photo_profil = $photo_profil;

        return $this;
    }


    public function getRoles(): array
    {
        return array($this->role ?? 'ROLE_USER');
    }

    public function getPassword(): string
    {
        return $this->mdp;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getSalt(): ?string
    {
        return null; 
    }

    public function eraseCredentials(): void
    {
        
    }

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Recette::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $recettes;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Note::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $notes;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Commentaire::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $commentaires;

    public function __construct()
    {
        $this->recettes = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function getRecettes(): Collection
    {
        return $this->recettes;
    }

    public function addRecette(Recette $recette): self
    {
        if (!$this->recettes->contains($recette)) {
            $this->recettes[] = $recette;
            $recette->setUtilisateur($this);
        }

        return $this;
    }

    public function removeRecette(Recette $recette): self
    {
        if ($this->recettes->contains($recette)) {
            $this->recettes->removeElement($recette);
            if ($recette->getUtilisateur() === $this) {
            }
        }

        return $this;
    }

}

templates/connexion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="bg-white shadow-sm p-5 rounded" style="max-width: 800px; margin: 0 auto;">
        <h2 class="text-center mb-4" style="color: #F4A261;">Connexion</h2>

        <div class="container">
            {% for message in app.flashes('error') %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endfor %}
        </div>

        <form action="{{ path('app_login') }}" method="post">
            <div class="mb-3">
                <label for="email" class="form-label">Adresse e-mail</label>
                <input type="email" name="_username" id="email" class="form-control"
                       placeholder="Entrez votre email"
                       value="{{ last_username }}" required>
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Mot de passe</label>
                <input type="password" name="_password" id="password"
                       class="form-control"
                       placeholder="Entrez votre mot de passe" required>
            </div>

            <div class="text-center mt-4">
                <button type="submit" class="btn"
                        style="background-color: #F4A261; color: white; width: 100%;">
                    Se connecter
                </button>
            </div>
        </form>

        <div class="mt-3 text-center">
            <a href="{{ path('mot_de_passe_oublie') }}" style="color: #F4A261; text-decoration: none;">Mot de passe oublié ?</a>
            <br><br>
            <h6 class="text-muted">- OU -</h6>
            <br>
            <a href="{{ path('app_register') }}" class="btn"
               style="background-color: white; color: #F4A261; border: 1px solid #F4A261;">
                S'inscrire
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/info-recette.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ recette.titre }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block content %}
<div class="row mb-5">
    <div class="col-md-6">
        <img src="{{ asset('images/recettes/' ~ recette.image) }}" alt="{{ recette.titre }}" class="img-fluid rounded shadow m-2" style="height:350px; width:100%; object-fit: cover;">
    </div>
    <div class="col-md-6">
        <br>
        <h1 class="fw-bold text-uppercase">{{ recette.titre }}</h1>
        <div class="d-flex align-items-center mb-3">
            {% if recette.utilisateur.photoProfil %}
                <img src="{{ asset('images/profils/' ~ recette.utilisateur.photoProfil) }}" alt="Photo de {{ recette.utilisateur.nom }}" class="rounded-circle me-2" style="width: 40px; height: 40px; object-fit: cover;">
            {% endif %}
            <p class="text-muted mb-0" style="font-size: 0.9em;">Par {{ recette.utilisateur.nom }}</p>
        </div>
        <p class="lead">{{ recette.description }}</p>

        <div class="my-3">
            <strong>Note moyenne :</strong>
            {% if moyenne %}
                <span class="star-rating">
                    {% for i in 1..5 %}
                        <i class="fas fa-star{% if i > moyenne %}-o{% endif %}"></i>
                    {% endfor %}
                    ({{ moyenne|number_format(1, '.', ',') }}/5)
                </span>
            {% else %}
                <em>Pas encore de note</em>
            {% endif %}
        </div>

        {% if app.user %}
            {% if not note_deja_donnee %}
                <div class="my-3">
                    <strong>Notez cette recette :</strong>
                    {{ form_start(formNote, {'attr': {'id': 'form-note'}}) }}
                    {{ form_widget(formNote.note, {
                        'attr': {
                            'class': 'd-none',
                            'id': 'note_note'
                        }
                    }) }}
                    <div class="d-flex gap-2">
                        {% for i in 1..5 %}
                            <input type="radio" class="btn-check" name="note_etoile" id="note_{{ i }}" value="{{ i }}">
                            <label class="btn btn-outline-warning px-2 py-1" for="note_{{ i }}">
                                <i class="fas fa-star"></i>
                            </label>
                        {% endfor %}
                    </div>
                    {{ form_end(formNote) }}
                </div>
            {% else %}
                <p class="text-success mt-3">Vous avez déjà noté cette recette, merci !</p>
            {% endif %}
        {% else %}
            <p class="text-muted">Connectez-vous pour noter cette recette.</p>
        {% endif %}
    </div>
</div>
<div class="border rounded p-4 mt-4 w-100" style="min-width: 100%;">
    <h4><i class="fas fa-utensils"></i> Ustensiles</h4>
    <div class="d-flex flex-wrap gap-3 justify-content-start">
        {% for ustensile in recette.ustensiles %}
            <div class="d-flex align-items-center gap-2 border rounded px-4 py-3" style="min-width: 200px;">
                {% if ustensile.nom starts with 'http' %}
                    <img src="{{ ustensile.nom }}" alt="{{ ustensile.nom }}" style="width: 24px; height: 24px;">
                {% else %}
                    <i class="{{ ustensile.nom }}"></i>
                {% endif %}
                <span>{{ ustensile.description }}</span>
            </div>
        {% endfor %}
    </div>
</div>

<hr>

<h2><i class="fas fa-carrot"></i> Ingrédients</h2>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
    {% for detenir in recette.detenir %}
        <div class="col">
            <div class="border rounded p-3 h-100 d-flex align-items-center bg-light shadow-sm">
                <i class="fas me-3 text-success" style="font-size: 1.5rem;"></i>
                <div>
                    <strong>{{ detenir.ingredient.nom|capitalize }}</strong><br>
                    <small class="text-muted">{{ detenir.quantite }} {{ detenir.unite }}</small>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<hr>

<h2><i class="fas fa-list-ol"></i> Étapes</h2>
<div>
    {% for etape in recette.etapes %}
        <div class="etape">
            <h5>Étape {{ loop.index }}</h5>
            <p>{{ etape.description }}</p>
        </div>
    {% endfor %}
</div>

<hr>

<h2><i class="bi bi-chat-dots"></i> Commentaires</h2>

{% if app.user %}
    <div class="mt-5">
        <h4>Laisser un commentaire</h4>
        {% if errorMessage %}
            <div class="alert alert-danger">
                {{ errorMessage }}
            </div>
        {% endif %}
        {{ form_start(formCommentaire) }}
            <div class="mb-3">
                {{ form_label(formCommentaire.texte) }}
                {{ form_widget(formCommentaire.texte, {'attr': {'class': 'form-control'}}) }}
            </div>
            <button type="submit" class="btn text-white" style="background-color: #F4A261;">Envoyer</button>
        {{ form_end(formCommentaire) }}
    </div>
{% else %}
    <p class="text-muted">Connectez-vous pour laisser un commentaire.</p>
{% endif %}

<br>
<div>
    {% for commentaire in recette.commentaires %}
        <div class="commentaire">
            <div class="d-flex align-items-center mb-2">
                {% if commentaire.utilisateur.photoProfil %}
                    <img src="{{ asset('images/profils/' ~ commentaire.utilisateur.photoProfil) }}" alt="Photo de {{ commentaire.utilisateur.nom }}" class="rounded-circle me-2" style="width: 30px; height: 30px; object-fit: cover;">
                {% endif %}
                <strong>{{ commentaire.utilisateur.nom }}</strong>
                <span class="text-muted ms-2" style="font-size: 0.9em;">le {{ commentaire.dateCommentaire|date('d/m/Y') }}</span>
            </div>
            <p>{{ commentaire.texte }}</p>
        </div>
    {% else %}
        <p>Aucun commentaire pour le moment.</p>
    {% endfor %}
</div>

<script src="{{ asset('js/note.js') }}"></script>
{% endblock %}

templates/mot_de_passe_oublie.html.twig
{# templates/securite/mot_de_passe_oublie.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublié{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Mot de passe oublié</h2>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}

    <form method="post">
        <div class="form-group">
            <label for="email">Votre adresse email</label>
            <input type="email" name="email" class="form-control" required>
        </div>
        <button class="btn btn-primary mt-3">Envoyer le lien</button>
    </form>
</div>
{% endblock %}

templates/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil{% endblock %}

{% block content %}
<div class="container mt-5">
    
    <div class="bg-white shadow-sm p-5 rounded" style=" margin: 0 auto;">
        <div class="text-center">
            <div class="text-center position-relative">
                <form id="form-upload" action="{{ path('upload_photo_profil') }}" method="POST" enctype="multipart/form-data">
                    <label for="photoInput" class="profile-picture" style="cursor:pointer; width: 100px; height: 100px; border-radius: 50%; background-color: #F4A261; display: flex; align-items: center; justify-content: center; font-size: 2rem; color: white; margin: 0 auto; position: relative; overflow: hidden;">
                        {% if utilisateur.photoProfil %}
                            <img src="{{ asset('images/profils/' ~ utilisateur.photoProfil) }}" alt="Profil" style="width:100%; height:100%; border-radius: 50%; object-fit: cover;">
                        {% else %}
                            {{ utilisateur.nom|slice(0, 1)|upper }}
                        {% endif %}
                        <div class="overlay" style="
                            position: absolute;
                            top: 0;
                            left: 0;
                            right: 0;
                            bottom: 0;
                            background: rgba(240, 240, 240, 0.7);
                            border-radius: 50%;
                            display: none;
                            align-items: center;
                            justify-content: center;
                            font-size: 2rem;
                            color: #333;
                            font-weight: bold;
                        ">
                            +
                        </div>
                    </label>
                    <input type="file" name="photo" id="photoInput" accept="image/*" style="display:none" onchange="document.getElementById('form-upload').submit();">
                </form>
            </div>
            <h3 class="mt-3">{{ utilisateur.nom }}</h3>
            <p class="text-muted">Membre depuis : {{ utilisateur.dateInscription|date('d/m/Y') }}</p>
        </div>
        
        <hr>

        <ul class="nav nav-tabs" id="profileTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="infos-tab" data-bs-toggle="tab" data-bs-target="#infos" type="button" style="color:#F4A261;" role="tab">Informations personnelles</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="recettes-tab" data-bs-toggle="tab" data-bs-target="#recettes" type="button" style="color:#F4A261;" role="tab">Mes Recettes</button>
            </li>
        </ul>

        <div class="tab-content mt-4" id="profileTabContent">
            <div class="tab-pane fade show active" id="infos" role="tabpanel">
                <form action="{{ path('modifier_profil') }}" method="POST">
                    <div class="row">
                        <div class="col-md-6">
                            <label class="form-label">Nom d'utilisateur</label>
                            <input type="text" name="nom" class="form-control" value="{{ utilisateur.nom }}" required>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Email</label>
                            <input type="email" name="email" class="form-control" value="{{ utilisateur.email }}" required>
                        </div>
                    </div>
                    <div class="text-center mt-4">
                        <button type="submit" class="btn" style="background-color:#F4A261; color:white;">Enregistrer</button>
                    </div>
                </form>
            </div>

            <div class="tab-pane fade" id="recettes" role="tabpanel">
                <div class="mt-3">
                    <h5>Mes Recettes</h5>
                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        {% for recette in pagination %}
                        
                            <div class="col">
                                <a href="{{ path('app_afficher_recette', {'id': recette.id}) }}" class="text-decoration-none text-dark">
                                    <div class="card border-0 shadow-sm h-100">
                                        <div class="position-relative">
                                            <img src="{{ asset('images/recettes/' ~ recette.image) }}" class="card-img-top rounded" style="height:300px;" alt="{{ recette.titre }}">
                                        </div>
                                        <div class="card-body text-center">
                                            <h5 class="card-title">{{ recette.titre|length > 20 ? recette.titre|slice(0, 20) ~ '...' : recette.titre }}</h5>
                                            <p class="mb-0">
                                                <span class="text-warning">
                                                    {% for i in 1..5 %}
                                                        {% if i <= recette.noteMoyenne %}
                                                            <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
                                                        {% else %}
                                                            <i class="fa-regular fa-star" style="color: #FFD43B;"></i>
                                                        {% endif %}
                                                    {% endfor %}
                                                </span>
                                                {{ recette.noteMoyenne|number_format(1, '.', ',') }}/5
                                            </p>
                                        </div>
                                    </div>
                                </a>

                                <div class="d-flex justify-content-center gap-2 mt-2">
                                    <a href="{{ path('modifier_recette', {'id': recette.id}) }}" class="btn btn-primary btn-sm">Modifier</a>
                                    <a href="{{ path('supprimer_recette', {'id': recette.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Voulez-vous vraiment supprimer cette recette ?')">Supprimer</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="col-12 text-center">
                                <p class="text-muted">Aucune recette publiée pour le moment.</p>
                            </div>
                        {% endfor %}
                    </div>
                    <br>
                    <br>
                    {% if pagination.pageCount > 1 %}
                        <nav>
                            <ul class="pagination justify-content-center">

                                {# Bouton Précédent #}
                                <li class="page-item {% if pagination.currentPageNumber == 1 %}disabled{% endif %}">
                                    <a class="page-link"
                                    href="{{ path('app_profil', {'page': pagination.currentPageNumber - 1}) ~ '#recettes' }}"
                                    aria-label="Précédent">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>

                                {# Liens de page #}
                                {% for i in 1..pagination.pageCount %}
                                    <li class="page-item {% if pagination.currentPageNumber == i %}active{% endif %}">
                                        <a class="page-link"
                                        href="{{ path('app_profil', {'page': i}) ~ '#recettes' }}">{{ i }}</a>
                                    </li>
                                {% endfor %}

                                {# Bouton Suivant #}
                                <li class="page-item {% if pagination.currentPageNumber == pagination.pageCount %}disabled{% endif %}">
                                    <a class="page-link"
                                    href="{{ path('app_profil', {'page': pagination.currentPageNumber + 1}) ~ '#recettes' }}"
                                    aria-label="Suivant">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>

                            </ul>
                        </nav>
                    {% endif %}
                    <div class="mt-4 text-center">
                        <a href="{{ path('ajouter_recette') }}" class="btn btn-success">Ajouter une recette</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


    <script src="{{ asset('js/profil.js') }}"></script>
{% endblock %}

templates/reinitialiser_mot_de_passe.html.twig
{# templates/securite/reinitialiser_mot_de_passe.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Réinitialiser le mot de passe{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Réinitialiser votre mot de passe</h2>

    <form method="post">
        <div class="form-group">
            <label for="mot_de_passe">Nouveau mot de passe</label>
            <input type="password" name="mot_de_passe" class="form-control" required>
        </div>
        <button class="btn btn-success mt-3">Changer le mot de passe</button>
    </form>
</div>
{% endblock %}